import { NextRequest, NextResponse } from 'next/server'
import { getAnalytics } from '../../analytics'
import { aggregateScoutingReport, ScoutingReport } from '../../analytics/scoutingReport'
import { storeJSON, readJSON } from '../../storage'

/**
 * GET - Fetch existing scouting report
 */
export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams
  const teamId = searchParams.get('teamId')
  
  if (!teamId) {
    return NextResponse.json({ error: 'teamId is required' }, { status: 400 })
  }
  
  const reportKey = `scouting-reports/team_${teamId}.json`
  const report = await readJSON<ScoutingReport>(reportKey)
  
  if (!report) {
    return NextResponse.json({ error: 'No scouting report found' }, { status: 404 })
  }
  
  return NextResponse.json(report)
}

/**
 * POST - Generate scouting report for a team
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { teamId, teamName, seriesList } = body
    
    if (!teamId || !teamName || !seriesList || !Array.isArray(seriesList)) {
      return NextResponse.json(
        { error: 'teamId, teamName, and seriesList are required' },
        { status: 400 }
      )
    }
    
    console.log(`Generating scouting report for ${teamName} with ${seriesList.length} series`)
    
    const analyticsResults: { seriesId: string; analytics: any; opponent: string; date: string }[] = []
    const errors: string[] = []
    
    // Process each series - analytics should already be generated by the per-series calls
    for (let i = 0; i < seriesList.length; i++) {
      const series = seriesList[i]
      console.log(`Collecting analytics ${i + 1}/${seriesList.length}: ${series.id}`)
      
      try {
        // Analytics should already exist from per-series processing
        const analytics = await getAnalytics(series.id)
        
        if (analytics) {
          analyticsResults.push({
            seriesId: series.id,
            analytics,
            opponent: series.opponent || 'Unknown',
            date: series.date || '',
          })
        } else {
          console.warn(`No analytics found for series ${series.id}`)
        }
      } catch (error) {
        console.error(`Error collecting series ${series.id}:`, error)
        errors.push(`Series ${series.id}: ${error instanceof Error ? error.message : 'Unknown error'}`)
      }
    }
    
    if (analyticsResults.length === 0) {
      return NextResponse.json(
        { error: 'No analytics could be generated', details: errors },
        { status: 500 }
      )
    }
    
    // Aggregate into scouting report
    const report = aggregateScoutingReport(teamId, teamName, analyticsResults)
    
    // Store the report
    const reportKey = `scouting-reports/team_${teamId}.json`
    await storeJSON(reportKey, report)
    
    console.log(`Scouting report generated for ${teamName}: ${analyticsResults.length} series analyzed`)
    
    return NextResponse.json({
      success: true,
      report,
      seriesProcessed: analyticsResults.length,
      errors: errors.length > 0 ? errors : undefined,
    })
  } catch (error) {
    console.error('Error generating scouting report:', error)
    return NextResponse.json(
      { error: 'Failed to generate scouting report' },
      { status: 500 }
    )
  }
}
